using System;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.IO;
using System.Linq;
using System.Text;

namespace WD.SoapGen.Code
{
    public record ServiceFile(NamespaceDeclarationSyntax Namespace, IEnumerable<CSharpSyntaxNode> Types)
    {
        public override string ToString()
        {
            var b = new StringBuilder(AUTO_GENERATED);

            b.Append($"namespace {Namespace.Name.ToFullString()}");
            b.AppendLine("{");

            foreach (var ty in Types)
            {
                b.Append(ty.ToFullString());
            }

            b.AppendLine("}");

            return b.ToString();
        }

        const string AUTO_GENERATED = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
"
;
    }
}
